version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
hooks:
  BeforeInstall:
    - location: strapi-web-app/scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: strapi-web-app/scripts/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: strapi-web-app/scripts/verify_service.sh
      timeout: 300
      runas: root