version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - echo pre-build
  build:
    commands:
      - echo Build started on `date`
      - echo date
  post_build:
    commands:
      # copy the contents of /build to S3
      - ls -ltr
      # - aws s3 cp --recursive --acl public-read s3://${DeployBucket}/
artifacts:
  files:
    - '**'
    - '**/*'
    - 'strapi-web-app/**'
    - 'strapi-web-app/scripts/**/*'
    - 'strapi-web-app/scripts/nginx.conf'
  base-directory: .